# Generated by Django 5.2.4 on 2025-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='بنر صفحه اصلی')),
                ('type', models.CharField(blank=True, choices=[('slider', 'Slider'), ('banner', 'Banner'), ('features', 'Features')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنر های صفحه اصلی',
            },
        ),
    ]
