# Generated by Django 5.2.4 on 2025-08-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitesetting_alter_footerlink_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='image',
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(max_length=40, verbose_name='دسته بندی لینک'),
        ),
    ]
