# Generated by Django 5.2.4 on 2025-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_remove_footerlink_image_alter_footerlink_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/trust-symbol', verbose_name='عکس نماد اعتماد')),
            ],
            options={
                'verbose_name': 'نماد اعتماد',
                'verbose_name_plural': 'نماد های اعتماد',
            },
        ),
    ]
