# Generated by Django 5.2.4 on 2025-08-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0010_header_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['order'], 'verbose_name': 'هدر', 'verbose_name_plural': 'هدر ها'},
        ),
    ]
