# Generated by Django 5.2.4 on 2025-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0011_alter_header_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_title',
            field=models.CharField(default='درباره ما', max_length=10, verbose_name='عنوان درباره ما'),
        ),
    ]
