# Generated by Django 5.2.4 on 2025-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0014_rename_imageurl_sitesetting_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(default='درباره ما', max_length=100, verbose_name='عنوان درباره ما'),
        ),
    ]
