# Generated by Django 5.2.4 on 2025-08-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0016_remove_bannerimages_type_bannerimages_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimages',
            old_name='sub_title',
            new_name='subtitle',
        ),
    ]
