# Generated by Django 5.2.4 on 2025-08-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0017_rename_sub_title_bannerimages_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimages',
            name='price',
        ),
    ]
