# Generated by Django 5.2.4 on 2025-07-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_expiringtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringToken',
        ),
    ]
