# Generated by Django 5.2.4 on 2025-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0006_province_user_birthdate_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(default="")
        ),
    ]
