# Generated by Django 5.2.4 on 2025-11-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0007_alter_address_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.IntegerField(),
        ),
    ]
