# Generated by Django 5.2.4 on 2025-11-11 08:59
import os, pathlib
import json
from django.db import migrations

def load_cities_and_provinces(apps, schema_editor):
    Province = apps.get_model('account_module', 'Province')
    City = apps.get_model('account_module', 'City')

    base_dir = pathlib.Path(__file__).parent.parent.absolute()
    data_dir = base_dir / "data" / "cities_and_provinces.json"

    with open(data_dir, encoding='utf-8') as f:
        data = json.load(f)

    for obj in data:
        province_name = obj['province']
        for city_name in obj['cities']:
            province, _ = Province.objects.get_or_create(name=province_name)
            city = City.objects.get_or_create(province=province, name=city_name)


def unload_cities_and_provinces(apps, schema_editor):
    City = apps.get_model('your_app', 'City')
    Province = apps.get_model('your_app', 'Province')
    City.objects.all().delete()
    Province.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0009_alter_address_postal_code"),
    ]

    operations = [
        migrations.RunPython(load_cities_and_provinces, reverse_code=unload_cities_and_provinces),
    ]
