# Generated by Django 5.2.4 on 2025-11-13 09:17

import account_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0010_load_initial_cities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default=account_module.models.get_image,
                null=True,
                upload_to="images/profiles",
                verbose_name="پروفایل کاربر",
            ),
        ),
    ]
