# Generated by Django 5.2.4 on 2025-11-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0011_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fullname",
        ),
    ]
