# Generated by Django 5.2.4 on 2025-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0012_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "این نام کاربری از قبل استفاده شده است."},
                max_length=150,
                unique=True,
            ),
        ),
    ]
