# Generated by Django 5.2.4 on 2025-08-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/trust_symbol', verbose_name='عکس نماد اعتماد')),
            ],
            options={
                'verbose_name': 'نماد اعتماد',
                'verbose_name_plural': 'نماد های اعتماد',
            },
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(max_length=40, verbose_name='دسته بندی لینک'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(verbose_name='لینک', max_length=40),
        ),
        migrations.AlterField(
            model_name='footerlinkbox',
            name='title',
            field=models.CharField(max_length=40, verbose_name='عنوان دسته بندی لینک'),
        ),
    ]
