# Generated by Django 5.2.4 on 2025-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_trustsymbol_alter_footerlink_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustSymbol',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/footer', verbose_name='عکس فوتر'),
        ),
    ]
