# Generated by Django 5.2.4 on 2025-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_delete_trustsymbol_footerlink_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_logo', models.ImageField(upload_to='images/site-setting', verbose_name='لوگوی سایت', max_length=100)),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما صفحه اصلی')),
                ('about_us_logo', models.ImageField(upload_to='images/site-setting', verbose_name='عکس درباره ما صفحه اصلی')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.CharField(max_length=60, verbose_name='ایمیل')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='دسته بندی لینک'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='لینک', max_length=40),
        ),
    ]
