# Generated by Django 5.2.4 on 2025-08-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_trustsymbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='footer_link_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_link', to='site_module.footerlinkbox', verbose_name='دسته بندی'),
        ),
    ]
