# Generated by Django 5.2.4 on 2025-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_alter_footerlink_footer_link_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان هدر')),
                ('url', models.CharField(blank=True, null=True, verbose_name='لینک', max_length=100)),
            ],
            options={
                'verbose_name': 'هدر',
                'verbose_name_plural': 'هدر ها',
            },
        ),
    ]
