# Generated by Django 5.2.4 on 2025-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
