# Generated by Django 5.2.4 on 2025-08-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0012_sitesetting_about_us_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='about_us_logo',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='about_us_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='about_us_title',
            new_name='title',
        ),
    ]
