# Generated by Django 5.2.4 on 2025-08-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_rename_about_us_logo_sitesetting_imageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='imageUrl',
            new_name='imageurl',
        ),
    ]
