# Generated by Django 5.2.4 on 2025-08-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0015_alter_sitesetting_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimages',
            name='type',
        ),
        migrations.AddField(
            model_name='bannerimages',
            name='price',
            field=models.CharField(default='', verbose_name='قیمت محصولات', max_length=100),
        ),
        migrations.AddField(
            model_name='bannerimages',
            name='sub_title',
            field=models.CharField(default='', max_length=100, verbose_name='زیر عنوان'),
        ),
        migrations.AddField(
            model_name='bannerimages',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='عنوان بنر'),
        ),
    ]
