# Generated by Django 5.2.4 on 2025-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0018_remove_bannerimages_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlink",
            name="url",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="لینک"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="url",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="لینک"
            ),
        ),
    ]
