# Generated by Django 5.2.4 on 2025-11-11 12:00
import json
import pathlib
from django.db import migrations
from django.core.files import File


def load_initial_site_pictures(apps, schema_editor):
    SiteSetting = apps.get_model('site_module', 'SiteSetting')
    FooterLink = apps.get_model('site_module', 'FooterLink')
    FooterLinkBox = apps.get_model('site_module', 'FooterLinkBox')
    Header = apps.get_model('site_module', 'Header')
    TrustSymbols = apps.get_model('site_module', 'TrustSymbols')
    BannerImages = apps.get_model('site_module', 'BannerImages')
    Category = apps.get_model('product_module', 'ProductCategory')
    Product = apps.get_model('product_module', 'Product')

    base_dir = pathlib.Path(__file__).parent.absolute()
    data_folder = base_dir / "initial_data"
    footer_badge_images_dir = data_folder / "symbols"
    logo_path = data_folder / 'logo.png'
    initial_values_path = data_folder / 'initial_values.json'
    category_images_path = data_folder / "categories"
    product_image_path = data_folder / "product.jpg"
    main_page_banner_path = data_folder / 'main_page_banner.jpg'

    # trust symbol in footer
    for i in range(1, 3):
        with open(footer_badge_images_dir / f"{i}.png", mode='rb') as f:
            TrustSymbols.objects.get_or_create(
                image=File(f, name=f"{i}.png")
            )

    # site text stuff, footer and header links and site logo
    with (open(initial_values_path, mode='utf-8') as init_file,
          open(logo_path, mode='rb') as logo):
        initial_values = json.load(init_file)

        site_setting, created = SiteSetting.objects.get_or_create(
            site_name=initial_values['site_name'],
            site_logo=File(logo, name='logo.png'),
            title=initial_values['aboutus_title'],
            text=initial_values['aboutus_text'],
            phone=initial_values['phone'],
            email=initial_values['email'],
            address=initial_values['address'],
        )

        for key, val in initial_values['header_links']:
            Header.objects.get_or_create(
                title=val,
                url=key,
            )

        for name in initial_values['footer_link_boxes']:
            FooterLinkBox.objects.get_or_create(
                title=name
            )

    # sites main banner in the home page
    with open(main_page_banner_path, mode='rb') as main_banner_img:

        banner, created = BannerImages.objects.get_or_create(
            title="خوش آمدید",
            subtitle="نوشیدنی ها اماده هستند",
            image=File(main_banner_img, name="main_page_banner.jpg")
        )

    # make some initial categories and products
    for i in range(1, 3):
        with open(category_images_path / f"{i}.png", mode='rb') as category_img:
            category, _ = Category.objects.get_or_create(title=f"{i}قهوه ",
                                                         image=File(category_img, name=f"{i}.png"))
            for j in range(1, 3):
                with open(product_image_path, mode="rb") as product_img:
                    Product.objects.get_or_create(title=f"{i * j}محصول ",
                                                  slug=f"{i * j}محصول ",
                                                  image=File(product_img, name=f"{i}.png"),
                                                  category=category,
                                                  price=100 * i,
                                                  discount=i * 2)


class Migration(migrations.Migration):
    dependencies = [
        ("site_module", "0019_alter_footerlink_url_alter_header_url"),
    ]

    operations = [
        migrations.RunPython(load_initial_site_pictures)
    ]
