# Generated by Django 5.2.4 on 2025-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0020_load_initial_site_pictures"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("instagram", models.CharField(max_length=255)),
                ("telegram", models.CharField(max_length=255)),
                ("whatsapp", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
