# Generated by Django 5.2.4 on 2025-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0022_contactusmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactusinfo",
            name="work_hours",
            field=models.CharField(default="working from 11 to 12", max_length=255),
            preserve_default=False,
        ),
    ]
