# Generated by Django 5.2.4 on 2025-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, error_messages={'unique': 'این شماره تلفن در سیستم وجود دارد.'}, unique=True),
        ),
    ]
