# Generated by Django 5.2.4 on 2025-10-23 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0014_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('iban', models.CharField(max_length=36, verbose_name='شماره شبا')),
                ('account_number', models.CharField(max_length=12, verbose_name='شماره حساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
