# Generated by Django 5.2.4 on 2025-10-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0015_bankinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinformation',
            old_name='account_number',
            new_name='accountNumber',
        ),
        migrations.RenameField(
            model_name='bankinformation',
            old_name='card_number',
            new_name='cardNumber',
        ),
    ]
