# Generated by Django 5.2.4 on 2025-10-23 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0016_rename_account_number_bankinformation_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_infos', to=settings.AUTH_USER_MODEL),
        ),
    ]
