# Generated by Django 5.2.4 on 2025-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
