# Generated by Django 5.2.4 on 2025-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("پرداخت سفارش", "Order"),
                    ("شارژ کیف پول", "WalletCharge"),
                    ("برداشت از کیف پول", "WalletWithdraw"),
                ],
                default="شارژ کیف پول",
                max_length=20,
            ),
        ),
    ]
