# Generated by Django 5.2.4 on 2025-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(
                blank=True,
                default="INTERNAL<function uuid4 at 0x000002C6CAA7ADE0>",
                max_length=100,
                null=True,
            ),
        ),
    ]
