# Generated by Django 5.2.4 on 2025-11-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, default='INTERNAL<function uuid4 at 0x000001C0C40177E0>', max_length=100, null=True),
        ),
    ]
