# Generated by Django 5.2.4 on 2025-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='تصویر مقاله')),
                ('short_description', models.CharField(verbose_name='توضیحات کوتاه مقاله')),
                ('full_description', models.TextField(verbose_name='توضیحات تکمیلی مقاله')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
