# Generated by Django 5.2.4 on 2025-08-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_articlecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی مقاله'),
        ),
    ]
