# Generated by Django 5.2.4 on 2025-09-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_alter_article_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jalali_created_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
