# Generated by Django 5.2.4 on 2025-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0004_article_jalali_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="jalali_created_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="short_description",
            field=models.CharField(max_length=100, verbose_name="توضیحات کوتاه مقاله"),
        ),
    ]
