# Generated by Django 5.2.4 on 2025-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0005_alter_article_jalali_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="توضیحات کوتاه مقاله"
            ),
        ),
    ]
