# Generated by Django 5.2.4 on 2025-11-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0006_alter_article_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
