# Generated by Django 5.2.4 on 2025-07-29 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='برند محصول')),
                ('image', models.ImageField(upload_to='images/brands', verbose_name='عکس برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories', verbose_name='عکس دسته بندی')),
                ('link', models.CharField(blank=True, null=True, verbose_name='لینک مقصد', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', null=True, max_length=100)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='عکس محصول')),
                ('slug', models.SlugField(blank=True, default='', null=True, max_length=255)),
                ('short_description', models.CharField(blank=True, null=True, verbose_name='توضیحات کوتاه', max_length=255)),
                ('description_title', models.CharField(blank=True, null=True, verbose_name='عنوان توضیحات', max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('price', models.CharField(verbose_name='قیمت محصولات', max_length=20)),
                ('discount', models.CharField(blank=True, max_length=20, null=True, verbose_name='تخفیف')),
                ('discounted_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='قیمت تخفیف خورده')),
                ('is_done', models.BooleanField(default=False, verbose_name='تمام شده / نشده')),
                ('is_done_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تمام شد')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت محصول')),
                ('jalali_created_date', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.brand', verbose_name='برند محصول')),
                ('category', models.ManyToManyField(to='product_module.productcategory', verbose_name='دسته بندی محصول')),
                ('product_tag', models.ManyToManyField(to='product_module.producttag', verbose_name='تگ محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('jalali_created_date', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده / نشده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcomment', verbose_name='والد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت محصول',
                'verbose_name_plural': 'کامنت های محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product-gallery', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='گالری محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='ویژگی')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('product', models.ManyToManyField(related_name='properties', to='product_module.product')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصول',
            },
        ),
    ]
