# Generated by Django 5.2.4 on 2025-08-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='product',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='product_module.product'),
        ),
    ]
