# Generated by Django 5.2.4 on 2025-11-04 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0011_order_orderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=100, verbose_name="عنوان بنر"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/category_banner", verbose_name="بنر دسته بندی"
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر دسته بندی",
                "verbose_name_plural": "بنر های دسته بندی",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.IntegerField(blank=True, null=True, verbose_name="قیمت نهایی"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product_module.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="عنوان توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=100, verbose_name="قیمت محصولات"),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="توضیحات کوتاه"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="link",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="لینک مقصد"
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.CharField(blank=True, max_length=64, null=True)),
                ("ref_id", models.CharField(blank=True, max_length=64, null=True)),
                ("gateway", models.CharField(default="zarinpal", max_length=20)),
                ("is_successful", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="product_module.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "واریز"), ("debit", "برداشت")],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("card", "کارت"), ("iban", "شبا")], max_length=10
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="product_module.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("authority", models.CharField(blank=True, max_length=255, null=True)),
                ("ref_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_successful", models.BooleanField(default=False)),
                ("gateway", models.CharField(default="zarinpal", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="product_module.wallet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
