# Generated by Django 5.2.4 on 2025-11-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0012_categorybanner_product_final_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="product_module.productcategory",
                verbose_name="دسته بندی محصول",
            ),
        ),
    ]
