# Generated by Django 5.2.4 on 2025-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0014_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveBigIntegerField(
                blank=True, max_length=20, null=True, verbose_name="تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.BigIntegerField(
                blank=True, max_length=20, null=True, verbose_name="قیمت تخفیف خورده"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="final_price",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="قیمت نهایی"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(
                max_length=100, verbose_name="قیمت محصولات"
            ),
        ),
    ]
