# Generated by Django 5.2.4 on 2025-11-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0015_alter_product_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="قیمت تخفیف خورده"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(verbose_name="قیمت محصولات"),
        ),
    ]
