# Generated by Django 5.2.4 on 2025-11-05 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0017_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="قیمت تخفیف خورده"
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product_module.product",
                verbose_name="گالری محصول",
            ),
        ),
    ]
