# Generated by Django 5.2.4 on 2025-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0018_alter_product_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
