# Generated by Django 5.2.4 on 2025-11-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0019_product_is_active"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transaction",
            new_name="WalletTransaction",
        ),
    ]
