# Generated by Django 5.2.4 on 2025-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0020_rename_transaction_wallettransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
