# Generated by Django 5.2.4 on 2025-11-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0021_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("کیف پول", "Wallet"), ("درگاه پرداخت", "PaymentGateway")],
                default="کیف پول",
                max_length=20,
            ),
        ),
    ]
