# Generated by Django 5.2.4 on 2025-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0022_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("کیف پول", "Wallet"),
                    ("درگاه پرداخت", "PaymentGateway"),
                    ("پرداخت در محل", "COD"),
                ],
                default="کیف پول",
                max_length=20,
            ),
        ),
    ]
