# Generated by Django 5.2.4 on 2025-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0023_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                blank=True, default="zarinpal", max_length=20, null=True
            ),
        ),
    ]
