# Generated by Django 5.2.4 on 2025-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0024_alter_payment_gateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[("credit", "واریز"), ("debit", "برداشت"), ("order", "سفارش")],
                max_length=10,
            ),
        ),
    ]
