# Generated by Django 5.2.4 on 2025-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0025_alter_wallettransaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
