# Generated by Django 5.2.4 on 2025-11-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0026_alter_product_slug_alter_productcategory_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBannerGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="images/category-gallery"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product_module.productcategory",
                    ),
                ),
            ],
        ),
    ]
