# Generated by Django 5.2.4 on 2025-11-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0027_categorybannergallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
    ]
