# Generated by Django 5.2.4 on 2025-11-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0028_alter_product_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryBanner",
        ),
    ]
