# Generated by Django 5.2.4 on 2025-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0030_product_is_featured_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_purchasable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="قیمت محصولات"
            ),
        ),
    ]
