# Generated by Django 5.2.4 on 2025-08-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_done_image',
        ),
    ]
