# Generated by Django 5.2.4 on 2025-08-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_remove_product_is_done_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_tag',
        ),
    ]
