# Generated by Django 5.2.4 on 2025-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jalali_created_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
