# Generated by Django 5.2.4 on 2025-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
