# Generated by Django 5.2.4 on 2025-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_product_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='images/category_banner', verbose_name='بنر دسته بندی')),
            ],
            options={
                'verbose_name': 'بنر دسته بندی',
                'verbose_name_plural': 'بنر های دسته بندی',
            },
        ),
    ]
