# Generated by Django 5.2.4 on 2025-09-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_article_jalali_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jalali_created_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
